name: Build scribble docs
on:
  push:
    branches:
      - main

    paths:
      - 'scribblings/**'

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: install racket
        uses: Bogdanp/setup-racket@v0.10
        with:
          distribution: 'full'
          variant: 'regular'
          version: '7.8'
          
      - name: Install Nocell
        run: raco pkg install --auto

      - run: raco scribble --htmls --dest doc --redirect-main https://docs.racket-lang.org +m scribblings/docs.scrbl
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/grid
          CLEAN: true
